language: python

python:
  - "3.6"
  - "3.7"


install:
  - pip install -r requirements.txt
  
script: true
  - nosetests --with-coverage --coverage report
  
script: 
  - python TestCalculate.py


deploy:
  provider: heroku
  api_key:
    secure: b2f1307c9ff36088328a37753e7678bd999201de
  app: test-my-travisci-project0
  on:
    repo: 00657106/GitExample
