language: python

python:
  - "3.6"
  - "3.7"


install:
  - pip install -r requirements.txt
  
script: true
  - nosetests --with-coverage --coverage report
  
script: 
  - python TestCalculate.py

deploy:
  provider: heroku
  api_key:
    secure: 9bd27f81-0ac9-432a-a7fb-10daa7d9dc41
  app: test-my-travisci-project
  on:
    repo:00657106/GitExample
