language: python

python:
  - "3.6"
  - "3.7"


install:
  - pip install -r requirements.txt
  
script: true
  - nosetests --with-coverage --coverage report
  
script: 
  - python TestCalculate.py


deploy:
  provider: heroku
  api_key:
    secure: 11a898eebb548abee46c7ae752080d51697dfd9b
  app: test-my-travisci-project0
  on:
    repo: 00657106/GitExample
