language: python

python:
   - "3.6"
   - "3.7"


install:
  - pip install -r requirements.txt
  
script: true
  - nosetests --with-coverage --coverage report
  
script: 
  - python TestCalculate.py

deploy:
  provider: heroku
  api_key:
    secure: a22b0e87-4967-4f62-9e61-06fa916da954/d14b2fb3-cc57-4b4b-8567-d3b970185c17
  app: test-my-travisci-project0
  on:
    repo: 00657106/GitExample
